"""Add image on class Post

Revision ID: 426fc674ac78
Revises: 173cb58e68a0
Create Date: 2019-09-25 13:59:21.825229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426fc674ac78'
down_revision = '173cb58e68a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('design_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'design_image')
    # ### end Alembic commands ###
