"""Add title attribute to comments

Revision ID: 87884bd8fb3a
Revises: 
Create Date: 2019-09-27 09:27:03.377592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87884bd8fb3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'title')
    # ### end Alembic commands ###
